create table QUESTION
(
    ID            INTEGER AUTO_INCREMENT PRIMARY KEY ,
    TITLE         VARCHAR(50),
    DESCRIPTION   TEXT,
    GMU_CREATE    BIGINT,
    GMT_MODIFIED  BIGINT,
    CREATOR       INTEGER,
    COMMENT_COUNT INTEGER default 0,
    VIEW_COUNT    INTEGER default 0,
    LIKE_COUNT    INTEGER default 0,
    TAG           VARCHAR(256)
);
